#!/bin/env bash

CONFIG="$(pwd)/config.sh"

source ./src/main.sh

function main() {
	while [[ $# != 0 ]]; do
		case "$1" in
		build | apply)
			ACTION="$1"
			shift
			;;
		-h | --help)
			# print help
			exit
			;;
		-c | --config)
			CONFIG="$2"
			break
			;;
		*)
			logError "Unknown option: $1"
			exit
			;;
		esac
	done

	# Setting up state and generations
	initState "$CONFIG"

	# Setting up current generation
	#initGeneration

	# Executing action
	$ACTION "$CONFIG"
}

main "$@"

# FOR TESTING
#
#for i in "${!loadedOptions[@]}"; do
#	echo "$i: ${loadedOptions[$i]}"
#done

#for i in "${!loadedModules[@]}"; do
#	executeModule "${loadedModules[$i]#*:}"
#done
#for i in "${!loadedModules[@]}"; do
#	echo "${loadedModules[$i]%:*}"
#done

#if hasModule "sway"; then
#	echo "yes"
#else
#	echo "no"
#fi

#l=${#loadedModules[@]}
#for (( i=0; i < ${l}; i++ )); do
#	echo $i ${loadedModules[$i]}
#done
#for file in $(tree -aifF --noreport ./modules | grep -v '/$'); do
#	echo "Reading file $file..."
#	if [ -f $file ]; then
#		source $file
#		echo $env
#	fi
#done
